title:  余林翼
description: My Personal Stack Problems
author: Jacksparrów
github: https://jacksparrow.cn
about: 致虚极、守静笃
disqus_shortname: stackproblems
google_analytics: UA-XXXXXXXX-Y

enableTags: true
tagarray: []

collections:
  project:
    output: true
    permalink: /project/:path/

social:
    - icon: fa-globe-americas
      link: "#"
    - icon: fa-twitter
      link: "#"
    - icon: fa-futbol
      link: "#"
    - icon: fa-hippo
      link: "#"
    - icon: fa-github
      link: "https://github.com/Yulinyi"

urls:
    - text: About Me
      url: /about/
    # - text: My Projects
      # url: /projects/
    # - text: XML Feed
    #   url: /feed.xml

url: "https://jacksparrow.cn"
baseurl: ""
paginate: 30
per_page: 50
paginate_path: "/page/:num/"
markdown: kramdown
gems:
  - jekyll-paginate
  - jekyll-gist

compress_html:
  clippings: all
  comments: ["<!-- ", " -->"]
  endings: all
  ignore:
    envs: ['development']
